### ISSUE TITLE
YOUR ideas

### ISSUE THREAD

**Issue by mpawlak2** [mpawlak2/instalike-instagram-bot#17]
Post your ideas here. New functionality, enhancements, anything goes!

I will start: add proxy support.

**Comment by virginsince1997** [comment]
How to make LIKEFEEDMEDIA bot like recently uploaded pictures on my feed , it just likes sporadically..... @mpawlak2

**Comment by mpawlak2** [comment]
@virginsince1997 yep, it likes random pictures from feed and also from tags since you cant disable that. You want it to like every picture in your feed and only those?

**Comment by virginsince1997** [comment]
Yes sir

**Comment by virginsince1997** [comment]
Since newly uploaded feeds would be coming in with less amount of likes,
what do you think I should set
MinLikesOnPhoto and MinLikesOnPhoto to? ,  or that doesn't include the
feeds, tags only?

**Comment by mpawlak2** [comment]
@virginsince1997 since you want to like every picture set it to 0 :)

**Comment by tim-peters** [comment]
As far as I understand the unfollow function isn't implemented yet. Right? Is there anything we can support you with? Automatic unfollowing of people who did not follow back after some time would be pretty, pretty useful.

**Comment by mpawlak2** [comment]
@tim-peters actually it is, check out INSTAFOLLOW::UnfollowAfterNoOfDays on readme page

**Comment by tim-peters** [comment]
Oh.. I was kinda irritated by the sentence `Unfollowing functionality in progress.` on the readme page.

Does the script need to run non-stop for the defined amount of days or is it based on the follow times saved in the database? Because after > a week of following people, I restarted the script with `UNFOLLOW USERS` set to `True` and `UnfollowAfterNoOfDays` set to `1` and it still does not unfollow anyone.
